from __future__ import annotations

import jinja2 as jinja2
import pydantic as pydantic
from jinja2 import Environment, Template
from pydantic import BaseModel, Field, TypeAdapter

from .agent import (
    AgentResponse,
    AgentRunError,
    AgentStreamEvent,
    AgentUIHandlers,
    AssistantMessageData,
    AssistantMessageDeltaData,
    AssistantThinkingDeltaData,
    Client,
    ClientOptions,
    CreateSessionOptions,
    Profile,
    ProfileInput,
    RunOptions,
    Session,
    SpawnedProcess,
    SpawnFunction,
    SpawnOptions,
    ToolCallData,
    ToolResultData,
)
from .api import (
    AgentEndEvent,
    AgentInitEvent,
    AgentStartEvent,
    CommandPassResult,
    CommandRespondResult,
    CommandResult,
    CommandRunAgentResult,
    EmptyEvent,
    EventBlock,
    EventName,
    EventResult,
    Extension,
    ExtensionEvent,
    ResourcesDiscoverEvent,
    SessionEndEvent,
    SessionStartEvent,
    SystemPromptPatch,
    ToolCallDetails,
    ToolCallEvent,
    ToolExecutionResult,
    ToolListPatch,
    ToolResultDetails,
    ToolResultEvent,
    TurnEndEvent,
    TurnStartEvent,
    UserMessageEvent,
    create_extension_host,
    define_extension,
    on,
)
from .context import (
    CommandContext,
    CommandFlagValue,
    CommandInvocation,
    EnvContext,
    EventContext,
    ExecResult,
    FileInfo,
    FileSystemContext,
    HostRPCClient,
    LogContext,
    PathContext,
    ProcessContext,
    ProcessExecOptions,
    ProcessSpawnOptions,
    SharedContext,
    StorageContext,
    ToolContext,
    UIConfirmRequest,
    UIContext,
    UIInputRequest,
    UIInputResponse,
    UIInputStatus,
    UINotifyRequest,
    UISelectRequest,
    run_with_host_rpc_client,
    set_active_host_rpc_client,
)
from .runtime import run_extension
from .template import render_template
from .test_harness import ExtensionTestHarness, create_test_harness

ExtensionHost = Extension
Pydantic = pydantic
Jinja2 = jinja2

__all__ = [
    "AgentEndEvent",
    "AgentInitEvent",
    "AgentResponse",
    "AgentRunError",
    "AgentStartEvent",
    "AgentStreamEvent",
    "AgentUIHandlers",
    "AssistantMessageData",
    "AssistantMessageDeltaData",
    "AssistantThinkingDeltaData",
    "BaseModel",
    "Client",
    "ClientOptions",
    "CommandContext",
    "CommandFlagValue",
    "CommandInvocation",
    "CommandPassResult",
    "CommandRespondResult",
    "CommandResult",
    "CommandRunAgentResult",
    "CreateSessionOptions",
    "EmptyEvent",
    "EnvContext",
    "Environment",
    "EventBlock",
    "EventContext",
    "EventName",
    "EventResult",
    "ExecResult",
    "Extension",
    "ExtensionEvent",
    "ExtensionHost",
    "ExtensionTestHarness",
    "Field",
    "FileInfo",
    "FileSystemContext",
    "HostRPCClient",
    "Jinja2",
    "LogContext",
    "PathContext",
    "ProcessContext",
    "ProcessExecOptions",
    "ProcessSpawnOptions",
    "Profile",
    "ProfileInput",
    "Pydantic",
    "ResourcesDiscoverEvent",
    "RunOptions",
    "Session",
    "SessionEndEvent",
    "SessionStartEvent",
    "SharedContext",
    "SpawnFunction",
    "SpawnOptions",
    "SpawnedProcess",
    "StorageContext",
    "SystemPromptPatch",
    "Template",
    "ToolCallData",
    "ToolCallDetails",
    "ToolCallEvent",
    "ToolContext",
    "ToolExecutionResult",
    "ToolListPatch",
    "ToolResultData",
    "ToolResultDetails",
    "ToolResultEvent",
    "TurnEndEvent",
    "TurnStartEvent",
    "TypeAdapter",
    "UIConfirmRequest",
    "UIContext",
    "UIInputRequest",
    "UIInputResponse",
    "UIInputStatus",
    "UINotifyRequest",
    "UISelectRequest",
    "UserMessageEvent",
    "create_extension_host",
    "create_test_harness",
    "define_extension",
    "jinja2",
    "on",
    "pydantic",
    "render_template",
    "run_extension",
    "run_with_host_rpc_client",
    "set_active_host_rpc_client",
]
